import type { CommodityType } from './types';

export const SPEC_FIELDS: Record<CommodityType, { key: string; label: string }[]> = {
  chrome: [
    { key: 'cr2o3_pct', label: 'Cr\u2082O\u2083 (%)' },
    { key: 'fe_pct', label: 'Fe (%)' },
    { key: 'sio2_pct', label: 'SiO\u2082 (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  manganese: [
    { key: 'mn_pct', label: 'Mn (%)' },
    { key: 'fe_pct', label: 'Fe (%)' },
    { key: 'sio2_pct', label: 'SiO\u2082 (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  iron_ore: [
    { key: 'fe_pct', label: 'Fe (%)' },
    { key: 'sio2_pct', label: 'SiO\u2082 (%)' },
    { key: 'al2o3_pct', label: 'Al\u2082O\u2083 (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  coal: [
    { key: 'cv_kcal', label: 'Calorific Value (kcal/kg)' },
    { key: 'ash_pct', label: 'Ash (%)' },
    { key: 'volatile_pct', label: 'Volatile Matter (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  aggregates: [
    { key: 'particle_size_mm', label: 'Particle Size (mm)' },
    { key: 'density', label: 'Density (t/m\u00b3)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  platinum: [
    { key: 'pt_gpt', label: 'Pt (g/t)' },
    { key: 'pd_gpt', label: 'Pd (g/t)' },
    { key: 'rh_gpt', label: 'Rh (g/t)' },
    { key: 'purity_pct', label: 'Purity (%)' },
    { key: 'pgm_total_gpt', label: 'Total PGM (g/t)' },
  ],
  gold: [
    { key: 'fineness', label: 'Fineness' },
    { key: 'weight_troy_oz', label: 'Weight (troy oz)' },
    { key: 'au_pct', label: 'Au (%)' },
    { key: 'ag_ppm', label: 'Ag (ppm)' },
  ],
  copper: [
    { key: 'cu_pct', label: 'Cu (%)' },
    { key: 'as_ppm', label: 'As (ppm)' },
    { key: 'pb_ppm', label: 'Pb (ppm)' },
    { key: 'fe_ppm', label: 'Fe (ppm)' },
    { key: 's_ppm', label: 'S (ppm)' },
  ],
  vanadium: [
    { key: 'v2o5_pct', label: 'V\u2082O\u2085 (%)' },
    { key: 'fe_pct', label: 'Fe (%)' },
    { key: 'si_pct', label: 'Si (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
  ],
  titanium: [
    { key: 'tio2_pct', label: 'TiO\u2082 (%)' },
    { key: 'fe2o3_pct', label: 'Fe\u2082O\u2083 (%)' },
    { key: 'sio2_pct', label: 'SiO\u2082 (%)' },
    { key: 'moisture_pct', label: 'Moisture (%)' },
    { key: 'feedstock_type', label: 'Feedstock Type' },
  ],
};

export const SPEC_LABELS: Record<string, string> = {
  cr2o3_pct: 'Cr\u2082O\u2083 (%)',
  fe_pct: 'Fe (%)',
  sio2_pct: 'SiO\u2082 (%)',
  al2o3_pct: 'Al\u2082O\u2083 (%)',
  moisture_pct: 'Moisture (%)',
  mn_pct: 'Mn (%)',
  cv_kcal: 'Calorific Value (kcal/kg)',
  ash_pct: 'Ash (%)',
  volatile_pct: 'Volatile Matter (%)',
  particle_size_mm: 'Particle Size (mm)',
  density: 'Density (t/m\u00b3)',
  size_mm: 'Size (mm)',
  aav: 'AAV',
  crushing_value: 'Crushing Value',
  pt_gpt: 'Pt (g/t)',
  pd_gpt: 'Pd (g/t)',
  rh_gpt: 'Rh (g/t)',
  purity_pct: 'Purity (%)',
  pgm_total_gpt: 'Total PGM (g/t)',
  fineness: 'Fineness',
  weight_troy_oz: 'Weight (troy oz)',
  au_pct: 'Au (%)',
  ag_ppm: 'Ag (ppm)',
  cu_pct: 'Cu (%)',
  as_ppm: 'As (ppm)',
  pb_ppm: 'Pb (ppm)',
  fe_ppm: 'Fe (ppm)',
  s_ppm: 'S (ppm)',
  v2o5_pct: 'V\u2082O\u2085 (%)',
  si_pct: 'Si (%)',
  tio2_pct: 'TiO\u2082 (%)',
  fe2o3_pct: 'Fe\u2082O\u2083 (%)',
  feedstock_type: 'Feedstock Type',
};
